name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag 1c16cb0ae0a54a08beb5d6747fa04b55.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag 1c16cb0ae0a54a08beb5d6747fa04b55.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER 1c16cb0ae0a54a08beb5d6747fa04b55.azurecr.io/sample-app-aoai-chatgpt:latest;
        docker push 1c16cb0ae0a54a08beb5d6747fa04b55.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push 1c16cb0ae0a54a08beb5d6747fa04b55.azurecr.io/sample-app-aoai-chatgpt:latest;
      
